### ISSUE TITLE
"Object" argument is missing, with no default

### ISSUE THREAD

**Issue by Tezko** [ha-pu/globaltrends#106]
I got an error when I try to execute compute_score() function.

I have already downloaded control and object data from google trends, new_control and new_object are well created with their data, nothing seems missing in database, so I don't understand where the problem is.

![image](https://user-images.githubusercontent.com/16416077/100088544-952dcc00-2e50-11eb-868d-9c5373fa494b.png)

And there is file code : 

![image](https://user-images.githubusercontent.com/16416077/100088747-e9d14700-2e50-11eb-9090-3ce28af15f68.png)

**Comment by ha-pu** [comment]
I think the error is that you close the bracks before you enter the inputs. Could you change it to `compute_score(control = new_control, object = new_object)` and re-run it?

**Comment by Tezko** [comment]
Oh yes you're right, it's a stupid mistake, my IDE did an autocompletion and I didn't see that...

So now that the compute_score is called, I have this : **"Columns `hits` not found"** 

![image](https://user-images.githubusercontent.com/16416077/100108457-17c38500-2e6b-11eb-8188-c359812475fc.png)

But this column "hits" exists 

![image](https://user-images.githubusercontent.com/16416077/100108783-71c44a80-2e6b-11eb-8856-e8c6da0c7926.png)


![image](https://user-images.githubusercontent.com/16416077/100108841-86084780-2e6b-11eb-8f8a-3912ab5c7bd7.png)

**Comment by ha-pu** [comment]
I could recreate the error. The issue was related to a miss-named column in the `tibble` that is uploaded to the database. Fixed the issue.
